### ISSUE TITLE
Setup CeleBA dataset

### ISSUE THREAD

**Issue by HaaaO** [ahxt/fair_fairness_benchmark#2]
Hi, can I ask where I can download the "celebs.csv" dataset included in the line below? Also, it would be really appreciated if dataset setup process can be included in the documentations. 

"df = pd.read_csv( os.path.join(path, "celeba.csv"), na_values="NA", index_col=None, sep=",", header=0)"

Thanks!

**Comment by ahxt** [comment]
Thank you for your interest in our repo and great suggestions! I have updated the datasets and downloading instructions. Please let me know if you have any further questions.
