### ISSUE TITLE
Jigsaw Dataset Files Missing

### ISSUE THREAD

**Issue by e-delaney** [ahxt/fair_fairness_benchmark#4]
Thanks for the great work. When downloading the datasets from dropbox I noticed that jigsaw dataset was missing. Can you share the files mentioned in the below code? Also it would be great if you could provide information on how the protected attributes were binarized. 

```
def load_jigsaw_text_data(path="/data/han/data/fairness/jigsaw", sensitive_attribute="sex"):
    # | 48842 instances, mix of continuous and discrete(train=32561, test=16281)
    # | 45222 if instances with unknown values are removed(train=30162, test=15060)

    with open( os.path.join(path, "processed_text_features.pkl"), 'rb') as f:
```

Thanks.

**Comment by ahxt** [comment]
Have uploaded the processed Jigsaw dataset, please refer to /datasets/readme.md.

**Comment by e-delaney** [comment]
Thank you!
